const assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const port=4188,dir=fs.mkdtempSync(path.join(os.tmpdir(),'kantor-studio-'));
const request=async(route,body,method=body?'POST':'GET')=>{const response=await fetch(`http://127.0.0.1:${port}${route}`,{method,headers:{'content-type':'application/json'},body:body&&JSON.stringify(body)});return {status:response.status,body:await response.json()};};
const waitFor=async(check)=>{for(let i=0;i<100;i++){const value=await check();if(value)return value;await new Promise(r=>setTimeout(r,100));}throw new Error('Timed out');};
(async()=>{
  const server=spawn(process.execPath,[path.join(__dirname,'../server/server.js')],{env:{...process.env,PORT:String(port),DATA_DIR:dir,ENV_FILE:'/nonexistent',ANTHROPIC_API_KEY:'',DRY_RUN_DELAY_MS:'100'},stdio:['ignore','pipe','inherit']});let browser;
  try{
    await new Promise((resolve,reject)=>{server.stdout.on('data',d=>String(d).includes('Kantor Kita:')&&resolve());server.on('error',reject);server.on('exit',code=>reject(new Error('Server exited '+code)));});
    const created=(await request('/api/tasks',{title:'Launch announcement',assignee:'Kak Rani',brief:'Draft in Indonesian for existing customers; use only confirmed facts.'})).body;
    const draft=await waitFor(async()=>{const task=(await request('/api/tasks')).body.find(t=>t.id===created.id);return task?.status==='review'&&task;});
    assert.equal((await request('/api/reviews',{taskId:draft.id,version:0,members:['Kak Rani']})).status,409,'stale draft must be rejected');
    assert.equal((await request('/api/reviews',{taskId:draft.id,version:draft.version,members:['Koh Arman']})).status,400,'manual members must not be presented as AI');
    assert.equal((await request('/api/reviews',{taskId:draft.id,version:draft.version,members:['Kak Rani','Kak Rani']})).status,400);
    browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}`);await page.waitForFunction(()=>window.officeScene&&window.officeTasks.agentFor('Kak Rani'));await page.click('#bRoutine');
    const monitor=await page.evaluate(()=>officeScene.studioSnapshot().monitors.find(m=>m.member==='Kak Rani'));assert.equal(monitor.status,'Siap ditinjau');assert.equal(monitor.taskId,draft.id);
    // The visible screen itself is a task entry point, not just a label.
    await page.evaluate(()=>officeScene.setCamera({target:[5.5,10,-3.5],theta:Math.PI-.32,phi:.6,radius:30}));await page.waitForTimeout(200);/* On a slow CI renderer the camera may not have reached the new view yet, so the first click can miss: retry a few times. */for(let i=0;i<5&&!await page.evaluate(()=>document.getElementById('taskDialog').open);i++){await page.waitForTimeout(400);const point=await page.evaluate(()=>officeScene.monitorPoint('Kak Rani'));await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>document.getElementById('taskDialog').open,null,{timeout:4000}).catch(()=>{});}assert.ok(await page.evaluate(()=>document.getElementById('taskDialog').open),'clicking the monitor opens Tasks');assert.equal(await page.locator('#agentFilter').inputValue(),'Kak Rani');await page.click('#closeTasks');await page.click('#bReset');
    await page.evaluate(()=>officeScene.setCamera({target:[0,10,-3.5],theta:0,phi:.78,radius:35}));await page.waitForTimeout(200);const board=await page.evaluate(()=>officeScene.boardPoint());await page.mouse.click(board.x,board.y);await page.waitForFunction(()=>document.getElementById('workBoardDialog').open);assert.match(await page.locator('#workBoardItems').innerText(),/Launch announcement/);assert.match(await page.locator('#workBoardItems').innerText(),/UJI COBA/);
    await page.getByRole('button',{name:'Diskusikan draf ini',exact:true}).click();assert.match(await page.locator('#reviewSource').innerText(),/Draf versi/);await page.locator('#reviewPeople input[value="Kak Rani"]').check();await page.locator('#reviewPeople input[value="Kak Sinta"]').check();await page.locator('#reviewPeople input[value="Koh Arman"]').check();await page.check('#reviewUseAI');await page.fill('#reviewFocus','Check whether the message answers likely customer questions.');await page.click('#reviewMeetingForm button[type=submit]');await page.waitForFunction(()=>document.getElementById('reviewNotes').textContent.includes('Versi draf sumber'));assert.match(await page.locator('#reviewNotes').innerText(),/Customer Service/);assert.match(await page.locator('#reviewNotes').innerText(),/Colleague feedback/);assert.equal((await request('/api/tasks')).body.find(t=>t.id===draft.id).status,'review','meeting must not approve a draft');
    const download=page.waitForEvent('download');await page.click('#downloadReview');assert.equal((await download).suggestedFilename(),'kantor-review-notes.txt');await page.click('#endReview');await page.click('#closeReview');
    // Exact draft navigation and completion flow back into the work board and monitor.
    await page.click('#bLife');await page.click('#openResults');await page.getByRole('button',{name:'Buka tugas',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),`task-${draft.id}`);await page.getByRole('button',{name:'Setujui & selesaikan',exact:true}).click();await page.waitForFunction(()=>officeScene.studioSnapshot().monitors.find(m=>m.member==='Kak Rani').status==='Selesai');await page.click('#closeTasks');
    await page.click('#bLife');await page.click('#openResults');await page.selectOption('#workBoardFilter','done');assert.match(await page.locator('#workBoardItems').innerText(),/Selesai/);await page.click('#closeWorkBoard');await page.click('#bLife');
    const original=await page.evaluate(()=>officeScene.studioSnapshot().decorationColours);await page.selectOption('#chairStyle','sage');await page.selectOption('#rugStyle','slate');await page.selectOption('#plantStyle','autumn');await page.selectOption('#posterStyle','details');const updated=await page.evaluate(()=>officeScene.studioSnapshot());assert.notEqual(updated.decorationColours.chairs,original.chairs);assert.notEqual(updated.decorationColours.rugs,original.rugs);assert.notEqual(updated.decorationColours.plants,original.plants);assert.equal(updated.poster,'details');
    await page.selectOption('#officeWeather','rain');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().rain),true);const rain=await page.evaluate(()=>officeScene.studioSnapshot().rainSample);await page.waitForTimeout(200);assert.notDeepEqual(await page.evaluate(()=>officeScene.studioSnapshot().rainSample),rain);assert.equal(await page.evaluate(()=>officeStudio.audioSnapshot().playing),false);await page.click('#rainSound');assert.equal(await page.evaluate(()=>officeStudio.audioSnapshot().playing),true);await page.locator('#rainVolume').press('End');assert.equal(await page.evaluate(()=>officeStudio.audioSnapshot().volume),100);await page.click('#rainSound');assert.equal(await page.evaluate(()=>officeStudio.audioSnapshot().playing),false);
    await page.selectOption('#officeWeather','sunset');assert.equal(await page.evaluate(()=>officeScene.lifeSnapshot().mood),'evening');await page.selectOption('#officeWeather','rain');await page.click('#closeLife');await page.screenshot({path:path.join(os.tmpdir(),'kantor-studio-rain.png')});await page.reload();await page.waitForFunction(()=>window.officeScene);assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().appearance.chairs),'sage');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().rain),true);assert.equal(await page.evaluate(()=>officeStudio.audioSnapshot().playing),false,'sound must never autoplay after reload');
    await page.click('#bLife');await page.selectOption('#tourChoice','workspace');await page.click('#startTour');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().tour),'workspace');const theta=await page.evaluate(()=>officeScene.snapshot().camera.theta);await page.waitForTimeout(200);assert.notEqual(await page.evaluate(()=>officeScene.snapshot().camera.theta),theta);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().tour),null);
    for(const route of ['cat','building']){await page.click('#bLife');await page.selectOption('#tourChoice',route);await page.click('#startTour');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().tour),route);await page.click('#stopTour');assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().tour),null);}
    await page.click('#bLife');await page.click('#startTour');await page.mouse.move(650,350);await page.mouse.down();await page.mouse.move(690,370);await page.mouse.up();assert.equal(await page.evaluate(()=>officeScene.studioSnapshot().tour),null,'manual camera input stops tours');
    for(const width of [375,768,1440]){await page.setViewportSize({width,height:900});await page.click('#bLife');await page.locator('#officeAppearance').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.getElementById('lifeDialog').scrollWidth<=document.getElementById('lifeDialog').clientWidth));await page.screenshot({path:path.join(os.tmpdir(),`kantor-studio-${width}.png`)});await page.click('#closeLife');}
    const reduced=await browser.newPage({reducedMotion:'reduce'});reduced.on('pageerror',e=>errors.push(e.message));await reduced.goto(`http://127.0.0.1:${port}`);await reduced.waitForFunction(()=>window.officeScene);await reduced.click('#bLife');await reduced.click('#startTour');assert.equal(await reduced.evaluate(()=>officeScene.studioSnapshot().tour),null,'reduced motion uses a static tour view');
    const historical=(await request('/api/tasks',{title:'Historical draft',assignee:'Koh Arman',status:'done',result:'A confirmed draft for peer review.'})).body;
    const pending=request('/api/reviews',{taskId:historical.id,version:0,members:['Kak Rani','Kak Sinta']});await new Promise(r=>setTimeout(r,50));await request(`/api/tasks/${historical.id}`,{assignee:'Koh Wira'},'PATCH');assert.equal((await pending).body.stale,true,'changes during review must mark notes as stale');
    assert.deepEqual(errors,[]);console.log('PASS: monitor task entry, work board drafts/results, review guards and peer feedback without approval, decoration persistence, weather/audio, tours/manual interruption, responsive panels and reduced motion');
  }finally{if(browser)await browser.close();server.kill();fs.rmSync(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
